# Generated by Django 4.2.6 on 2023-10-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikect', '0004_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='create_at',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='update_at',
            new_name='time_update',
        ),
    ]
