# Generated by Django 4.2.6 on 2023-10-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikect', '0005_rename_create_at_ticket_time_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='content',
        ),
    ]
