# Generated by Django 4.2.6 on 2023-10-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikect', '0006_rename_description_review_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='description',
        ),
    ]
